### ISSUE TITLE
Cocoapods error caused by this plugin - JSON::ParserError - 743: unexpected token at ''

### ISSUE THREAD

**Issue by REPTILEHAUS** [stewwan/capacitor-fcm#21]
I cant build iOS at present because there seems to be some issue with the podfile in this plugins folder. Logged a bug over at cocoapods but removing this from my capacitor podfile allows the installation ```  pod 'CapacitorFcm', :path => '../../node_modules/capacitor-fcm'```

Here is the issue on Cocoapods repo https://github.com/CocoaPods/CocoaPods/issues/9311

**Comment by REPTILEHAUS** [comment]
Just curious I see this tutorial is for iOS and Android https://capacitor.ionicframework.com/docs/guides/push-notifications-firebase/ It appears to register android for an FCM token also so is there any need to use this plugin still or is capacitor now able to handle the whole process ?

**Comment by stewwan** [comment]
so weird, please provide reproducible sample so I can try to help

**Comment by stewwan** [comment]
closing. feel free to open a new issue if needed
