### ISSUE TITLE
Communication between two different apps

### ISSUE THREAD

**Issue by nielsvanrijn** [stewwan/capacitor-fcm#23]
Hi,

I'm building 2 ionic apps that have to send notifications to each other.
I created 2 different apps under the same Firebase Project (actually 4, iOS & Android), This in turn means I have 2 `GoogleService-Info.plist` files with the different `PRODUCT_BUNDLE_IDENTIFIER` names.

My problem is that only one of these `PRODUCT_BUNDLE_IDENTIFIER` and `GoogleService-Info.plist` combinations works. It looks like sending notifications between these two is impossible even tho they share the same Firebase Project and Cloud FireStore Database.

Is notification communication between two different apps with different `GoogleService-Info.plist` files possible?

**Comment by stewwan** [comment]
sorry it's too confusing, can you provide a reproducible environment?

**Comment by stewwan** [comment]
closing feel free to open a new issue with some steps to reproduce the problem.
