### ISSUE TITLE
Doco update: sample code has extra unnecessary }

### ISSUE THREAD

**Issue by Karrlllis** [stewwan/capacitor-fcm#24]
Hi @stewwan 

Thank you for the plugin!!! Works well with core capicator

In your sample code there are few unnecessary '}' after 
1) fcm
    .unsubscribeFrom
2) fcm
    .getToken()
3) fcm
    .deleteInstance()

**Comment by stewwan** [comment]
hey @Karrlllis 
you're right!
can you pr it?

thank you!
