### ISSUE TITLE
Ionic Capacitor-FCM - Error to subscribe/unsubscribe topic in iOS

### ISSUE THREAD

**Issue by pedroclericuzi** [stewwan/capacitor-fcm#33]
I followed all the steps from tutorial and in android is working fine, but in iOS is showing only this error  when I try subscribe or unsubscribe a topic:

`{"line":172816,"column":25,"sourceURL":"capacitor://localhost/vendor-es2015.js"}`

My infos:

Ionic:

   Ionic CLI                     : 5.4.16
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.900.6
   @angular-devkit/schematics    : 9.0.6
   @angular/cli                  : 9.0.6
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   Capacitor CLI   : 2.0.0
   @capacitor/core : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res (update available: 0.11.0) : 0.10.0
   native-run                             : not installed

System:

   NodeJS : v12.16.1 (/usr/local/bin/node)
   npm    : 6.13.4
   OS     : macOS Catalina
   Xcode  : Xcode 11.4 Build version 11E146

**Comment by stewwan** [comment]
can you please set up a reproducible example ?

**Comment by pedroclericuzi** [comment]
Hi, stewwan I resolved this problem. 
I only had added `pod 'CapacitorFcm', :path => '../../node_modules/capacitor-fcm'` in podfile and works fine!

**Comment by stewwan** [comment]
Thanks. Closing for now.. feel free to file a new issue if you find something odd.
