### ISSUE TITLE
2.0.0 release notes?

### ISSUE THREAD

**Issue by alexcroox** [stewwan/capacitor-fcm#35]
Just updating my deps and upgraded to 2.0.0 for this plugin. Since a major bump indicates breaking changes, is there a changelog anywhere I can read?

**Comment by stewwan** [comment]
yes there's a changelog in here but I've forgotten to update, will do on next release. thanks for the reminder. the only change was actually dependencies for android and capacitor v2. current api remains the same.

**Comment by alexcroox** [comment]
ah great thanks, I just migrated to Capacitor v2 as part of this 👍
