### ISSUE TITLE
[Android] Package io.stewan.capacitor.fcm.FCMPlugin does not exist

### ISSUE THREAD

**Issue by nikoskip** [stewwan/capacitor-fcm#5]
Hi,

I'm trying to use this plugin but I'm having trouble when I try to build on Android. I follow the README guide step by step but it seems that the Java package is not being included. These are the commands I'm running before building on Android Studio:

```
npm run build
npx cap copy 
npx cap open android
```

Any ideas?

Thanks!

**Comment by stewwan** [comment]
that's kinda weird. did you `npm install capacitor-fcm`?

also try to `invalidate cache and restart` on android studio before building

**Comment by nikoskip** [comment]
Yes, I have installed `capacitor-fcm`:

 ```
 "dependencies": {
    "@capacitor/android": "^1.0.0-beta.22",
    "@capacitor/cli": "^1.0.0-beta.22",
    "@capacitor/core": "^1.0.0-beta.22",
    "@ionic/core": "^4.3.1",
    "@ionic/vue": "0.0.4",
    "capacitor-fcm": "0.0.5",
    "core-js": "^2.6.5",
    "vue": "^2.6.10",
    "vue-audio-recorder": "^3.0.1",
    "vue-router": "^3.0.6"
  }
```
I just tried invalidating cache and restarting Android Studio with no luck.

Android Studio is unable to resolve the package 😢 

![image](https://user-images.githubusercontent.com/1230033/57412857-4235ea80-71c0-11e9-9a38-80bbbf8e024b.png)

**Comment by stewwan** [comment]
try this `import io.stewan.capacitor.fcm.FCMPlugin;`

**Comment by nikoskip** [comment]
It didn't work 😞 

![image](https://user-images.githubusercontent.com/1230033/57458185-e494b300-723e-11e9-897d-f185465b867d.png)

Any other ideas?

**Comment by nikoskip** [comment]
BTW, this is how I created my project: https://www.smashingmagazine.com/2018/07/mobile-apps-capacitor-vue-js/

I'm using Capacitor to build my native app and not Ionic. Could be the problem?

**Comment by stewwan** [comment]
Can you share a small repo?

I’ve tested only with ionic-angular but it's supposed to work with any
framework

**Comment by stewwan** [comment]
@nikoskip 

does this plugin module appear in Android studio?

also you must run `npx cap sync` after a plugin install

**Comment by nikoskip** [comment]
That was the solution, awesome! 

I really appreciate your help, thanks for your time 👍

**Comment by adelynx** [comment]
For the version `@capacitor-community/fcm` replace `import io.stewan.capacitor.fcm.FCMPlugin;` with `import com.getcapacitor.community.fcm.FCMPlugin;`
