### ISSUE TITLE
Android Build failed. unexpected char in _modules/capacitor-fcm/android\capacitor

### ISSUE THREAD

**Issue by xahanix** [stewwan/capacitor-fcm#8]
Hey.
I have a problem emulating my app with Android Studio.
The Project fails in the startup
I've done all the steps from the ReadMe.
It always shows this error:
![Unbenannt](https://user-images.githubusercontent.com/25527030/60297256-16192900-9928-11e9-9ab3-ffcf48c930c4.PNG)

Versions I use: 
 "@capacitor/android": "^1.1.0",
 "@capacitor/cli": "1.0.0-beta.22",
 "@capacitor/core": "1.0.0-beta.22",
 "@capacitor/ios": "^1.0.0",
 "capacitor-fcm": "0.0.6",

I've also done the extra step but it does'n even recognize io.stewan.capacitor.fcm.FCMPlugin
![Unbenannt](https://user-images.githubusercontent.com/25527030/60297497-9b044280-9928-11e9-9b26-8bdcf1490264.PNG)

Do you have any idea what the problem could be?

**Comment by xahanix** [comment]
Fixed the problem. Just had to change the \ in capacitor.settings.gradle to '/'. But every time I run "npx cap sync android". I have to change it again. Is someone else facing this problem?

**Comment by stewwan** [comment]
hey @xahanix 

maybe file an issue here?
https://github.com/ionic-team/capacitor/issues

or even post in slack channel, I'm sure someone from the core team should address this issue.
