### ISSUE TITLE
iOS FCM getToken

### ISSUE THREAD

**Issue by OrhanNasuf** [stewwan/capacitor-fcm#9]
How can we combine PushNotifications.addListener( 'registration')  with this plugin to receive an FCM token on iOS?

I have tried this (but the promise does not fire, so we never get the "fcm_token" below):
```

PushNotifications.addListener("registration", (token) => {
    fcm.getToken().then(fcm_token => console.log("FCM Token:", JSON.stringify(fcm_token))); 
});
```
In the xcode log all we see is that we receive APNS token and then:
...
To Native -> FCMPlugin getToken 655837

Any ideas?

**Comment by stewwan** [comment]
fix is on the way

**Comment by stewwan** [comment]
actually I made a mistake in a test, so there's no fix to do here.

just updated the demo project

@OrhanNasuf can you give it a shot?

https://github.com/stewwan/capacitor-fcm-demo

![ezgif-2-6d1022881ad1](https://user-images.githubusercontent.com/719763/60686663-8cfe7680-9e80-11e9-996c-4a57ad2393c7.gif)
